version: 1.0

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: Make all
          name: Test deployment

workflows:
  main:
    jobs:
      - build-and-test
